// src/components/layout/BottomNav.vue
<script setup lang="ts">
import { useRoute } from 'vue-router'

const route = useRoute()

const links = [
  { to: '/',            label: 'Pfad',       icon: '道' },
  { to: '/lernen/woerter', label: 'Wörter',  icon: '語' },
  { to: '/fortschritt', label: 'Fortschritt', icon: '歩' },
]

function isActive(to: string) {
  if (to === '/') return route.path === '/'
  return route.path.startsWith(to)
}
</script>

<template>
  <nav class="lg:hidden fixed bottom-0 inset-x-0 z-50 bg-surface border-t border-border safe-area-bottom">
    <div class="flex items-stretch justify-around h-16">
      <RouterLink
        v-for="link in links"
        :key="link.to"
        :to="link.to"
        class="flex flex-col items-center justify-center gap-0.5 flex-1 transition-colors"
        :class="isActive(link.to) ? 'text-primary' : 'text-text-muted hover:text-text'"
      >
        <span lang="ja" class="font-jp text-lg leading-none">{{ link.icon }}</span>
        <span class="font-sans text-[10px] tracking-wide">{{ link.label }}</span>
      </RouterLink>
    </div>
  </nav>
</template>

// src/components/layout/BottomNav.tsx
import { NavLink } from 'react-router-dom'
import { LayoutDashboard, FileText, Layers, HelpCircle, CalendarDays } from 'lucide-react'

const NAV_ITEMS = [
  { to: '/',        icon: LayoutDashboard, label: 'Home',    end: true },
  { to: '/notes',   icon: FileText,        label: 'Notizen', end: false },
  { to: '/decks',   icon: Layers,          label: 'Karten',  end: false },
  { to: '/quiz',    icon: HelpCircle,      label: 'Quiz',    end: false },
  { to: '/planner', icon: CalendarDays,    label: 'Planer',  end: false },
]

export default function BottomNav() {
  return (
    <nav
      className="fixed bottom-0 inset-x-0 md:hidden border-t z-50 flex items-center justify-around px-2 h-16"
      style={{ backgroundColor: 'var(--color-surface)', borderColor: 'var(--color-border)' }}
    >
      {NAV_ITEMS.map(({ to, icon: Icon, label, end }) => (
        <NavLink
          key={to}
          to={to}
          end={end}
          className={({ isActive }) =>
            `flex flex-col items-center gap-1 py-1.5 px-3 rounded-xl min-w-0 text-center transition-colors ${
              isActive ? 'nav-active' : 'nav-item'
            }`
          }
        >
          <Icon size={20} className="shrink-0" />
          <span className="text-[10px] font-medium leading-none">{label}</span>
        </NavLink>
      ))}
    </nav>
  )
}
