// src/components/layout/Sidebar.tsx
import { NavLink, useLocation } from 'react-router-dom'
import {
  LayoutDashboard, FileText, Layers, HelpCircle,
  CalendarDays, Settings, ChevronLeft, ChevronRight,
} from 'lucide-react'
import { useUIStore } from '@/store/uiStore'

const NAV_ITEMS = [
  { to: '/',        icon: LayoutDashboard, label: 'Dashboard', end: true },
  { to: '/notes',   icon: FileText,        label: 'Notizen',   end: false },
  { to: '/decks',   icon: Layers,          label: 'Karten',    end: false },
  { to: '/quiz',    icon: HelpCircle,      label: 'Quiz',      end: false },
  { to: '/planner', icon: CalendarDays,    label: 'Planer',    end: false },
]

export default function Sidebar() {
  const { sidebarOpen, setSidebarOpen } = useUIStore()
  const location = useLocation()
  const collapsed = !sidebarOpen

  return (
    <aside
      className={`hidden md:flex flex-col shrink-0 h-screen sticky top-0 border-r transition-all duration-200 ${collapsed ? 'w-[60px]' : 'w-56'}`}
      style={{ backgroundColor: 'var(--color-surface)', borderColor: 'var(--color-border)' }}
    >
      {/* Header */}
      <div
        className={`flex items-center h-14 px-3 border-b ${collapsed ? 'justify-center' : 'justify-between'}`}
        style={{ borderColor: 'var(--color-border)' }}
      >
        {!collapsed && (
          <span
            className="text-base font-bold tracking-tight"
            style={{ fontFamily: 'var(--font-heading)', color: 'var(--color-primary)' }}
          >
            Kitobi
          </span>
        )}
        <button
          onClick={() => setSidebarOpen(!sidebarOpen)}
          className="hidden lg:flex w-7 h-7 items-center justify-center rounded-md nav-item"
          title={collapsed ? 'Erweitern' : 'Minimieren'}
        >
          {collapsed ? <ChevronRight size={14} /> : <ChevronLeft size={14} />}
        </button>
      </div>

      {/* Navigation */}
      <nav className="flex-1 py-3 px-2 space-y-0.5 overflow-y-auto">
        {NAV_ITEMS.map(({ to, icon: Icon, label, end }) => (
          <NavLink
            key={to}
            to={to}
            end={end}
            className={({ isActive }) =>
              `flex items-center gap-3 px-2.5 py-2.5 rounded-lg text-sm ${collapsed ? 'justify-center' : ''} ${isActive ? 'nav-active' : 'nav-item'}`
            }
            title={collapsed ? label : undefined}
          >
            <Icon size={17} className="shrink-0" />
            {!collapsed && <span>{label}</span>}
          </NavLink>
        ))}
      </nav>

      {/* Settings at bottom */}
      <div className="px-2 pb-4">
        <NavLink
          to="/settings"
          className={`flex items-center gap-3 px-2.5 py-2.5 rounded-lg text-sm ${collapsed ? 'justify-center' : ''} ${location.pathname === '/settings' ? 'nav-active' : 'nav-item'}`}
          title={collapsed ? 'Einstellungen' : undefined}
        >
          <Settings size={17} className="shrink-0" />
          {!collapsed && <span>Einstellungen</span>}
        </NavLink>
      </div>
    </aside>
  )
}

// src/components/layout/SideBar.vue
<script setup lang="ts">
import { useRoute } from 'vue-router'
import { useAuthStore } from '@/stores/auth.store'
import KLogo from '@/components/ui/KLogo.vue'

const route = useRoute()
const auth = useAuthStore()

const links = [
  { to: '/',               label: 'Lernpfad',    icon: '道' },
  { to: '/lernen/woerter', label: 'Tagesvokabular', icon: '語' },
  { to: '/fortschritt',    label: 'Fortschritt',  icon: '歩' },
]

function isActive(to: string) {
  if (to === '/') return route.path === '/'
  return route.path.startsWith(to)
}
</script>

<template>
  <aside class="hidden lg:flex flex-col w-56 shrink-0 h-screen sticky top-0 bg-surface border-r border-border">
    <div class="flex items-center gap-3 px-4 h-16 border-b border-border">
      <KLogo size="md" class="shrink-0" />
      <div class="flex flex-col leading-tight">
        <span class="font-serif text-sm font-semibold tracking-[0.12em] text-text">KITOBI</span>
        <span lang="ja" class="font-jp text-xs text-text-muted">記飛</span>
      </div>
    </div>

    <nav class="flex flex-col gap-1 p-3 flex-1">
      <RouterLink
        v-for="link in links"
        :key="link.to"
        :to="link.to"
        class="flex items-center gap-3 px-3 py-2 rounded-md font-sans text-sm transition-colors"
        :class="isActive(link.to)
          ? 'bg-primary/10 text-primary font-medium'
          : 'text-text-muted hover:text-text hover:bg-bg'"
      >
        <span lang="ja" class="font-jp text-base w-5 text-center">{{ link.icon }}</span>
        {{ link.label }}
      </RouterLink>
    </nav>

    <div class="p-3 border-t border-border">
      <button
        @click="auth.logout()"
        class="w-full flex items-center gap-3 px-3 py-2 rounded-md font-sans text-sm text-text-muted hover:text-danger hover:bg-danger/5 transition-colors"
      >
        <span class="w-5 text-center">→</span>
        Abmelden
      </button>
    </div>
  </aside>
</template>
